sdt_captcha_extension.settings:
  type: config_object
  label: 'SDT Captcha extension configurations.'
  mapping:
    sdt_captcha_extension_enable_on_all_webforms:
      type: boolean
      label: 'Enable/Disable reCaptcha for all webforms'
