<?php

/**
 * @file
 * Contains sdt_captcha_extension.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function sdt_captcha_extension_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the sdt_captcha_extension module.
    case 'help.page.sdt_captcha_extension':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Recaptcha configuration') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter() to alter forms.
 */

function sdt_captcha_extension_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $webform_prefix = 'webform_submission';
  $is_webform = substr($form_id, 0, strlen($webform_prefix)) === $webform_prefix;
  $config = \Drupal::config('sdt_captcha_extension.settings');
  $is_captcha_enable = $config->get('sdt_captcha_extension_enable_on_all_webforms');
  $captcha_attributes = [
    '#type' => 'captcha',
    '#weight' => 10,
    '#captcha_type' => 'recaptcha/reCAPTCHA'
  ];

  if ($is_webform && $is_captcha_enable) {
    if (isset($form['elements']['container'])) {
      $form['elements']['container']['my_captcha_element'] = $captcha_attributes;
    } else {
      $form['elements']['my_captcha_element'] = $captcha_attributes;
      $form['elements']['actions']['#weight'] = 11;
    }
  }
}
