<?php

/**
 * @file
 * Contains google_workable_connector.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function google_workable_connector_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the google_workable_connector module.
    case 'help.page.google_workable_connector':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Make a request to Workable API. Retrieve the count of the active jobs. Get the published jobs listing.') . '</p>';
      return $output;

    default:
  }
}
/**
 * Implements hook_menu().
 */
function sgoogle_workable_connector_menu() {
  $items['admin/config/services/google-workable-connector'] = [
    'title' => 'Googel Workable Connector',
    'description' => 'Retrieve open positions posted on openwt.workable.com',
    'route_name' => 'google_workable_connector.config',
  ];
  return $items;
}
