google_workable_connector.settings:
  type: config_object
  label: 'Google Workable Connector config.'
  mapping:
    workable_api_key:
      type: string
      label: 'API token'
    workable_subdomain:
      type: string
      label: 'The accounts subdomain'
    workable_jobs_state:
      type: string
      label: 'Jobs publishing status'
    workable_cache_lifetime:
      type: integer
      label: 'Cache lifetime'
